### ISSUE TITLE
support | help?

### ISSUE THREAD

**Issue by superboxes** [hackorum/nvim#83]
I noticed that there arent any docs nor website as promised. Pushing away most users, maybe at least create a discord server for support for newbies such as myself as Im having a problem with dashboard because VapourNvim isnt documented

**Comment by krymancer** [comment]
I know its not the optimal way but if you click in the revisions number in wiki you can view older revisions with content.

From there you can acess other pages, like: https://github.com/VapourNvim/VapourNvim/wiki/Keybindings/c4a0ddab2c0be3d9c5bcff544139d4c1d5a590e4 for keybindings

**Comment by superboxes** [comment]
> I know its not the optimal way but if you click in the revisions number in wiki you can view older revisions with content.
> 
> From there you can acess other pages, like: https://github.com/VapourNvim/VapourNvim/wiki/Keybindings/c4a0ddab2c0be3d9c5bcff544139d4c1d5a590e4 for keybindings

thank you
