### ISSUE TITLE
E492: Not an editor command: PackerSync

### ISSUE THREAD

**Issue by Mandrew0822** [hackorum/nvim#85]
I get this when I run "curl -s https://raw.githubusercontent.com/VapourNvim/VapourNvim/main/install.sh | bash -s" in the terminal on Lmde

**Comment by dr-nemesis-96** [comment]
how about running this
@Mandrew0822 

git clone https://github.com/VapourNvim/VapourNvim ~/.config/nvim
nvim +PackerSync

**Comment by Mandrew0822** [comment]
Sorry, I get the same error
